name: Build ZMK Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git cmake ninja-build gperf \
          ccache dfu-util device-tree-compiler wget \
          python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file \
          make gcc g++ unzip
        pip install west

    - name: Initialize West and update modules
      run: |
        west init -l config
        west update

    - name: Build firmware
      run: |
        west build -s zmk/app -d build -b nice_nano_v2 -- -DSHIELD=my_6x15 -DZMK_CONFIG=../config
        cp build/zephyr/zephyr.uf2 firmware.uf2

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: firmware.uf2
