- name: Build firmware(s) from build.yaml
  run: |
    cd zmk
    while IFS= read -r line; do
      BOARD=$(echo "$line" | cut -d',' -f1)
      SHIELD=$(echo "$line" | cut -d',' -f2)
      echo "🔨 Building $BOARD + $SHIELD ..."
      west build -s app -d build/$BOARD-$SHIELD -b $BOARD \
        -- -DSHIELD=$SHIELD -DZMK_CONFIG=../config -DSHIELD_ROOT=../config/shields
      cp build/$BOARD-$SHIELD/zephyr/zephyr.uf2 ../firmware-${BOARD}-${SHIELD}.uf2
    done < <(yq -r '.include[] | "\(.board),\(.shield)"' ../build.yaml)
