name: Build ZMK Firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version data
        id: get_info
        run: |
          timestamp=$(date +"%Y%m%d%H%M")
          commit=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "file_prefix=$timestamp-$commit" >> $GITHUB_OUTPUT

      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: West Init
        run: west init -l config

      - name: West Update
        run: west update

      - name: West Zephyr export
        run: west zephyr-export

      - name: West Build (nice_nano_v2 + my_6x15)
        run: |
          west build -s zmk/app -d build/my_6x15 -b nice_nano_v2 \
            -- -DSHIELD=my_6x15 -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Rename firmware
        run: cp build/my_6x15/zephyr/zmk.uf2 ${{ steps.get_info.outputs.file_prefix }}-my_6x15.uf2

      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            ${{ steps.get_info.outputs.file_prefix }}-my_6x15.uf2
