- name: Checkout repository
  uses: actions/checkout@v4

- name: Clone ZMK
  run: git clone --recursive https://github.com/zmkfirmware/zmk.git zmk

- name: Initialize workspace
  run: |
    cd zmk
    west init -l .
    west update
    west zephyr-export
