- name: Upload firmware artifact
  uses: actions/upload-artifact@v4
  with:
    # ชื่อ artifact ที่จะแสดงบน GitHub Actions
    name: my_6x15_firmware
    # เส้นทางไปยังไฟล์ .uf2 ที่ถูกสร้างขึ้นหลัง build
    path: build/my_6x15/zephyr/zmk.uf2
    # Optional: หากต้องการรวมหลายไฟล์ ใช้ wildcards เช่น:
    # path: build/my_6x15/zephyr/*.uf2
    # Optional: กำหนด retention-days หากต้องการเก็บ artifact นานกว่า default
    # retention-days: 7
