name: Build ZMK Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Zephyr
      uses: zephyrproject-rtos/zephyr-action@v0.12.0

    - name: Install Python deps
      run: pip install west

    - name: Update west modules
      run: west update

    - name: Build firmware
      run: |
        west build -s app -d build -b nice_nano_v2 -- -DZMK_CONFIG=config
        cp build/zephyr/zephyr.uf2 zephyr.uf2

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: zephyr.uf2
