name: Build ZMK 6x15 firmware

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout config repository
      - uses: actions/checkout@v3

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build gperf ccache dfu-util \
            device-tree-compiler wget python3-pip python3-setuptools \
            python3-wheel xz-utils file make gcc

      # Install west
      - name: Install west
        run: pip3 install --user west

      # Clone ZMK release (v0.3.0)
      - name: Clone ZMK release
        run: |
          git clone --branch v0.3.0 --recurse-submodules https://github.com/zmkfirmware/zmk.git zmk

      # Build firmware
      - name: Build firmware
        run: |
          cd zmk
          west build -s app -b nice_nano_v2 \
            -d ../build/my_6x15 -- \
            -DSHIELD=my_6x15 \
            -DZMK_CONFIG=${GITHUB_WORKSPACE}/config

      # Upload firmware
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: my_6x15_firmware
          path: build/my_6x15/zephyr/zmk.uf2
